version: "3.8"

services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: trip-planner-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: tripplanner
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: tripplanner_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - backend

  osm2po:
    build:
      context: ./osm2po
      dockerfile: Dockerfile
    container_name: osm2po-container
    volumes:
      - ./osm_data:/osm_data
    depends_on:
      - postgres
    networks:
      - backend

  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - backend
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production
    networks:
      - backend
    depends_on:
      - server

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
