version: "3.8"

services:
  postgres:
    image: postgis/postgis:latest
    container_name: trip-planner-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=tripplanner
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=tripplanner_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sqlscripts:/docker-entrypoint-initdb.d  
    networks:
      - backend
  osm2po:
    image: openjdk:8-jre-slim
    container_name: osm2po-container
    build:
      context: ./osm2po
      dockerfile: Dockerfile
    command: /bin/bash -c 'if [ ! -f /usr/src/app/sqlscripts/hh_2po_4pgr.sql ]; then ./osm2po.sh; else echo "hh_2po_4pgr.sql already exists, skipping osm2po"; fi'
    networks:
      - backend
    depends_on:
      - postgres
  
  server:
    build:
      context: ./server
    ports:
      - "4000:4000"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - postgres

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - /app/node_modules
    environment:
      - NODE_ENV=production
    depends_on:
      - server

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
